# Generated by Django 6.0.4 on 2026-04-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vender_license',
            new_name='vendor_license',
        ),
    ]
