# Generated by Django 6.0.4 on 2026-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
