# Generated by Django 6.0.4 on 2026-05-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_openinghours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
    ]
