# Generated by Django 6.0.4 on 2026-05-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_rename_openinghours_openinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ('day', '-from_hour')},
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('vendor', 'day', 'from_hour', 'to_hour')},
        ),
    ]
