# Generated by Django 6.0.4 on 2026-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='prince',
            new_name='price',
        ),
    ]
